steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'MexSearch',
    '--runtime',
    'go113',
    '--trigger-http',
    '--set-env-vars',
    'SLACK_SECRET=${_SLACK_SECRET},SEARCH_API_KEY=${_SEARCH_API_KEY},SEARCH_ID=${_SEARCH_ID}'
  ]
